version: "3.9"

services:
  database:
    image: postgres:15
    container_name: kupipodariday-db
    restart: unless-stopped
    env_file: 
     - ./backend/.env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - kpd-network

  backend:
    build:
      context: ./backend
    container_name: kupipodariday-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "4000:3000" 
    depends_on:
      - database
    networks:
      - kpd-network

  frontend:
    build:
      context: ./frontend
    container_name: kupipodariday-frontend
    restart: unless-stopped
    ports:
      - "8081:80"  
    networks:
      - kpd-network
    depends_on:
    - backend  

volumes:
  db-data:

networks:
  kpd-network:
    driver: bridge
